const ONE_SECOND = 1000;
const THREE_SECONDS = 3 * ONE_SECOND;
const ONE_MINUTE = 60 * ONE_SECOND;
const ONE_HOUR = 60 * ONE_MINUTE;

export const timeoutInMS = {
  ONE_SECOND,
  THREE_SECONDS,
  ONE_MINUTE,
  ONE_HOUR,
};
